name: 'repo-health-score'
description: 'A repository overall health score from community profile metrics'
author: 'Fidel Alejandro Fernandez Arias'
branding:
  icon: 'check-circle'
  color: 'green'
inputs:
  token:
    description: Github token to grant access to the API and deploy the badge
    required: false
    default: ''
  php-version:
    description: 'Version of PHP'
    required: false
    default: '8.3'
runs:
  using: 'composite'
  steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php-version }}
        extensions: gd, curl, json

    - name: Install dependencies
      shell: bash
      working-directory: ${{ github.action_path }}
      run: composer install --no-dev --prefer-dist --no-interaction --no-progress

    - name: Generate badge
      shell: bash
      working-directory: ${{ github.action_path }}
      env:
        REPOSITORY: ${{ github.repository }}
        GITHUB_TOKEN: ${{ inputs.token || github.token }}
      run: php index.php

    - name: Deploy badge
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ inputs.token || github.token }}
        publish_dir: ${{ github.action_path }}/dist
        publish_branch: output
        force_orphan: true
