name: 'repo-health-score'
description: 'A repository overall health score from community profile metrics'
author: 'Fidel Alejandro Fernandez Arias'
branding:
  icon: 'check-circle'
  color: 'green'
inputs:
  php-version:
    description: 'Version of PHP'
    required: false
    default: 'latest'
runs:
  using: 'composite'
  steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php-version }}
        extensions: gd

    - name: Run composer
      uses: php-actions/composer@v6
      with:
        dev: no
        args: --profile --ignore-platform-reqs

    - name: Generate badge
      shell: bash
      env:
        REPOSITORY: ${{ github.repository }}
      run: php index.php