name: 'repo-health-score'
description: 'A repository overall health score from community profile metrics'
author: 'Fidel Alejandro Fernandez Arias'
branding:
  icon: 'check-circle'
  color: 'green'
inputs:
  token:
    description: Github token to grant access to deploy the badge
    required: true
  php-version:
    description: 'Version of PHP'
    required: false
    default: 'latest'
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v2
      with:
        repository: ale94lko/repo-health-score

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php-version }}
        extensions: gd

    - name: Run composer
      uses: php-actions/composer@v6
      with:
        dev: no
        args: --profile --ignore-platform-reqs

    - name: Generate badge
      shell: bash
      env:
        REPOSITORY: ${{ github.repository }}
      run: php index.php

    - name: Deploy badge
      uses: crazy-max/ghaction-github-pages@v3
      with:
        target_branch: output
        build_dir: dist
      env:
        GITHUB_TOKEN: ${{ inputs.token }}