name: Generate Badge
on:
  schedule: # execute every two minutes
    - cron: "*/2 * * * *"
  workflow_dispatch:
jobs:
  build:
    name: Job to deploy badge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Repo Health Score
        uses: ale94lko/repo-health-score@main

      - run: deploy.sh
        shell: bash