name: Generate Badge
on:
  schedule: # execute every two minutes
    - cron: "*/2 * * * *"
  workflow_dispatch:
jobs:
  build:
    name: Job to deploy badge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Repo Health Score
        uses: ale94lko/repo-health-score@main

      - uses: crazy-max/ghaction-github-pages@v3.0.0
        with:
          target_branch: output
          build_dir: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}