name: Generate Badge
on:
  schedule: # execute every two minutes
    - cron: "*/2 * * * *"
  workflow_dispatch:
jobs:
  build:
    name: Job to deploy badge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Repo Health Score
        uses: ale94lko/repo-health-score@main

      - shell: bash
        run: |
          set -e

          echo "::group::Push changes"
          git init

          git config user.email "github-action[bot]@noreply.github.com"
          git config user.name "github-actions[bot]"

          git add badge.svg
          git commit -m "deploy"

          git push -f "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git" main:output
          echo "::endgroup::"